In [7]:
# 1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives
import numpy as np

zeros_array = np.zeros(10)# Create an array of 10 zeros

ones_array = np.ones(10) # Create an array of 10 ones

fives_array = np.full(10, 5)# Create an array of 10 fives

print("Array of 10 zeros:")
print(zeros_array)

print("\nArray of 10 ones:")
print(ones_array)

print("\nArray of 10 fives:")
print(fives_array)

Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


In [8]:
# 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

values = np.arange(2, 11) # Generate values from 2 to 10

matrix = values.reshape(3, 3) # Reshape the array into a 3x3 matrix

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
# 3. Write a NumPy program to create an array with values ranging from 12 to 38.

# Generate values from 12 to 38
values = np.arange(12, 39)

print(values)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [10]:
# 4. Write a NumPy program to convert a list and tuple into arrays. Input: my_list = [1, 2, 3, 4, 5, 6, 7, 8] 
# Input: my_tuple = ([8, 4, 6], [1, 2, 3])
import numpy as np

my_list = [1, 2, 3, 4, 5, 6, 7, 8] # Input list

array_from_list = np.array(my_list) # Convert list to array

print("Array from list:")
print(array_from_list)

my_tuple = ([8, 4, 6], [1, 2, 3]) # Input tuple

array_from_tuple = np.array(my_tuple) # Convert tuple to array

print("\nArray from tuple:")
print(array_from_tuple)

Array from list:
[1 2 3 4 5 6 7 8]

Array from tuple:
[[8 4 6]
 [1 2 3]]
